### ISSUE TITLE
deal wit it

### ISSUE THREAD

**Issue by mcfnord** [AdamHale88/Repo1#1]
deeznutz

**Comment by AdamHale88** [comment]
D33zNU7$

**Comment by mcfnord** [comment]
You don't have to have a job writing JavaScript. I have a job writing Markdown. I can change Markdown, I can offer a pull request, and I can merge it. Do I need to write code for $51/hr? No! I only need to improve what's in some files. Coders and writers both have that in common. I can handle one or fifty files. I use simple tools to search and edit them. There are people who decide which code needs writing, there are people who write code, and there are people who write about the code. There are many different roles. So learn the fundamentals and then figure out your role. Coding was hard and stressful and I'm glad I don't do it for other people anymore.
